### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Kam0ss**
**Warning :** Before creating a pull request, make sure that it does not already exists in the [pull requests](../). Thank you.

## Description
Qc competition changes

## How has this been tested ?
Tested in competition

## Checklist
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by 0x72D0** [comment]
Wait I don't see that proc_detection call have been removed, isn't that going to fail at runtime?

**Comment by Kam0ss** [comment]
It was the competition build, we just need this merge to backup develop into master.

**Review by 0x72D0 — DISMISSED** [review]
LGTM!

**Comment by 0x72D0** [comment]
LGTM!

**Review by 0x72D0 — APPROVED** [review]
LGTM!

**Pull request merged**
